truncate TABLE dishCategory RESTART IDENTITY AND COMMIT;
truncate TABLE category RESTART IDENTITY AND COMMIT;
truncate TABLE file RESTART IDENTITY AND COMMIT;
truncate TABLE dishOrder RESTART IDENTITY AND COMMIT;
truncate TABLE orders RESTART IDENTITY AND COMMIT;
truncate TABLE dish RESTART IDENTITY AND COMMIT;
truncate TABLE name RESTART IDENTITY AND COMMIT;
truncate TABLE description RESTART IDENTITY AND COMMIT;
truncate TABLE partner RESTART IDENTITY AND COMMIT;








